README.md
1. the original instruction is a bit ambiguous as it doesn't specify where to add the `pod 'UberRides`.
2. for swift sdk users, the `use_frameworks!` line is necessary, otherwise `pod install` will exit with errors.
=> Improvements to the instructions

.gitignore
In case you use Pods, and do not store them in git, there is a point to add them ti .gitignore
=> Add: Pods to .gitignore

CHANGELOG.md, UberRides.podspec, source/UberRides.xcodeproj/project.pbxproj, source/UberRides/Configuration.swift, source/UberRides/Info.plist, source/UberRidesTests/AuthenticationURLUtilityTests.swift
Currently, using Carthage, it's not possible to upload an app to iTunesConnect. When uploading there are errors for invalid bundle.
http://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr
Frameworks do not require Copy Carthage but require Linked Libraries. See the instructions from Carthage's Readme.
Closes #49
=> Add ObjectMapper as a linked library instead of copy framework

source/UberRides/Model/RidesScope.swift, source/UberRidesTests/RidesScopeFactoryTests.swift
This seems to be a bug for missing out all the scope cases.
=> Fix RideScope not mapping for all cases

source/UberRides/Model/RideParameters.swift, source/UberRides/RequestDeeplink.swift, source/UberRides/RideRequestButton.swift, source/UberRides/RideRequestView.swift, source/UberRides/RideRequestViewController.swift, source/UberRides/RideRequestViewRequestingBehavior.swift, source/UberRidesTests/APIManagerTests.swift, source/UberRidesTests/DeeplinkRequestingBehaviorTests.swift, source/UberRidesTests/RequestButtonTests.swift, source/UberRidesTests/RequestDeeplinkTests.swift, source/UberRidesTests/RequestURLUtilTests.swift, source/UberRidesTests/RideParametersTest.swift, source/UberRidesTests/RideRequestViewControllerTests.swift, source/UberRidesTests/RideRequestViewRequestingBehaviorTests.swift, source/UberRidesTests/RideRequestViewTests.swift, source/UberRidesTests/RidesClientTests.swift, source/UberRidesTests/WidgetsEndpointTests.swift
Reduce complexity of the `RideParameters` model by removing the builder associated with it.
`RideParameters` represents the set of parameters sent via a deeplink, ride request widget, or the ride  estimate/request API endpoints. 
In the previous implementation, the primary thing the builder added was to ensure that the `RideParameters` were immutable. However, I don't think there is a huge issue around mutability with this model, and the builder pattern is not super common in Swift anyways.
=> Swifty APIs (Pt 2)

source/UberRides/AppStoreDeeplink.swift, source/UberRides/AuthenticationDeeplink.swift, source/UberRides/BaseDeeplink.swift, source/UberRides/Configuration.swift, source/UberRides/DeeplinkRequestingBehavior.swift, source/UberRides/LoginButton.swift, source/UberRides/ModalRideRequestViewController.swift, source/UberRides/ModalViewController.swift, source/UberRides/Model/RidesScope.swift, source/UberRides/OAuth/AuthorizationCodeGrantAuthenticator.swift, source/UberRides/OAuth/BaseAuthenticator.swift, source/UberRides/OAuth/ImplicitGrantAuthenticator.swift, source/UberRides/OAuth/LoginManager.swift, source/UberRides/OAuth/LoginView.swift, source/UberRides/OAuth/LoginViewAuthenticator.swift, source/UberRides/OAuth/NativeAuthenticator.swift, source/UberRides/RequestDeeplink.swift, source/UberRides/RideRequestButton.swift, source/UberRides/RideRequestView.swift, source/UberRides/RideRequestViewController.swift, source/UberRides/RideRequestViewRequestingBehavior.swift, source/UberRides/RidesAppDelegate.swift, source/UberRides/RidesClient.swift, source/UberRides/UberButton.swift, source/UberRidesTests/RidesMocks.swift
Currently, we have a hodgepodge between `public` and `open` APIs. 
Since `open` allows external developers to subclass, and we haven't explicitly designed for this situation, we should leave these classes as `public` for now.
=> Change open access control to public

source/UberRides/Model/RideParameters.swift, source/UberRides/RequestDeeplink.swift, source/UberRides/RideRequestButton.swift, source/UberRides/RideRequestView.swift, source/UberRides/RideRequestViewController.swift, source/UberRides/RideRequestViewRequestingBehavior.swift, source/UberRidesTests/APIManagerTests.swift, source/UberRidesTests/DeeplinkRequestingBehaviorTests.swift, source/UberRidesTests/RequestButtonTests.swift, source/UberRidesTests/RequestDeeplinkTests.swift, source/UberRidesTests/RequestURLUtilTests.swift, source/UberRidesTests/RideParametersTest.swift, source/UberRidesTests/RideRequestViewControllerTests.swift, source/UberRidesTests/RideRequestViewRequestingBehaviorTests.swift, source/UberRidesTests/RideRequestViewTests.swift, source/UberRidesTests/RidesClientTests.swift, source/UberRidesTests/WidgetsEndpointTests.swift
=> Add RideParametersBuilder

.gitmodules
There's no reason for us to check in git submodules for our dependencies since our `Cartfile` and `Cartfile.resolved` pins the versions that we're using already. 
This PR removes the Carthage submodules from our git repo.
=> Removed Carthage Checkouts folder

examples/Obj-C SDK/Obj-C SDK.xcodeproj/project.pbxproj, examples/Obj-C SDK/Obj-C SDK/AppDelegate.m, examples/Obj-C SDK/Obj-C SDK/Info.plist, examples/Obj-C SDK/Obj-C SDK/UBSDKDeeplinkExampleViewController.m, examples/Obj-C SDK/Obj-C SDK/UBSDKImplicitGrantExampleViewController.m, examples/Obj-C SDK/Obj-C SDK/UBSDKNativeLoginExampleViewController.m, examples/Obj-C SDK/Obj-C SDK/UBSDKRideRequestWidgetExampleViewController.m, examples/Swift SDK/Cartfile, examples/Swift SDK/Swift SDK.xcodeproj/project.pbxproj, examples/Swift SDK/Swift SDK/AppDelegate.swift, examples/Swift SDK/Swift SDK/AuthorizationCodeGrantExampleViewController.swift, examples/Swift SDK/Swift SDK/DeeplinkExampleViewController.swift, examples/Swift SDK/Swift SDK/ImplicitGrantExampleViewController.swift, examples/Swift SDK/Swift SDK/Info.plist, examples/Swift SDK/Swift SDK/NativeLoginExampleViewController.swift, examples/Swift SDK/Swift SDK/RideRequestWidgetExampleViewController.swift, source/UberRides/Model/RideParameters.swift, source/UberRides/Model/RidesScope.swift, source/UberRides/RideRequestViewController.swift, source/UberRides/UberButton.swift, source/UberRidesTests/AuthenticationDeeplinkTests.swift, source/UberRidesTests/AuthenticationURLUtilityTests.swift, source/UberRidesTests/BaseAuthenticatorTests.swift, source/UberRidesTests/LoginButtonTests.swift, source/UberRidesTests/LoginManagerTests.swift, source/UberRidesTests/OAuthTests.swift, source/UberRidesTests/OauthEndpointTests.swift, source/UberRidesTests/RidesScopeExtensionsTests.swift
Update sample projects so they work against the new SDK.
Fixes some oversights found in the SDK while updating the sample projects. Namely:
* Missing `@objc` annotation
* Incorrect capitalization for enum-style things.
Also adds a default Client ID for the sample projects so people can compile & go.
=> Swift 4 Example Projects

source/UberRides/Model/Driver.swift
Fixed a bug that caused a problem with loading the current ride because of null value for a driver sms number that we've received from API in Sandbox. Before that fix, when ride was in "accepted" state, we've received a json from API where sms number was null, so we were getting nil ride when calling "fetchCurrentRide" function because UberRides was decoding this json, and trying to get value for non optional String.
=> Driver smsNumber maked optional

source/UberRides/RideRequestViewController.swift, source/UberRidesTests/RideRequestViewControllerTests.swift
We update the `RideRequestViewController` to remove dependencies on the old `LoginView` and use the `LoginManager` to present the appropriate login flows instead. As you can see, it results in a net reduction of code :)
=> Update RideRequestViewController to use new Auth API

CHANGELOG.md, source/UberCore/Deeplinks/AppStoreDeeplink.swift, source/UberCore/Deeplinks/BaseDeeplink.swift, source/UberCore/Deeplinks/DeeplinkManager.swift, source/UberCore/Deeplinks/DeeplinkingProtocol.swift, source/UberCoreTests/BaseDeeplinkTests.swift
In the current SDK, deeplink objects are self-aware objects that manage their own state when executed.
This change turns deeplink objects into thin wrappers around the `URL` object, and separates out its state management (for performing the deeplink) into a manager singleton. This allows us to treat URLs as deeplinks (which they are, just for the Safari app). In addition, we get the ability to track deeplink success without necessarily having a `Deeplinking` object.
=> Move deeplink state management to dedicated manager class.

source/UberCore/Configuration.swift, source/UberCoreTests/ConfigurationTests.swift
Previously, the Configuration object kept track of Callback URIs as Strings. 
The correct type is `URL`, and upon the process of making changes to authenticators I decided to change this to `URL` across the board to reduce the need to convert between the two types. 
We also change the `useFallback` parameter to default false, as this parameter is only used to fall back to the Authorization Code flow. Since the end developer needs to set up a server to use Authorization Code flow, we make that usage opt-in.
=> Update Configuration to use `URL` for Callback URLs

CHANGELOG.md, source/UberCore/Authentication/Tokens/AccessToken.swift, source/UberCore/Authentication/Tokens/AccessTokenFactory.swift, source/UberCoreTests/AccessTokenFactoryTests.swift, source/UberCoreTests/OAuthTests.swift, source/UberCoreTests/RefreshEndpointTests.swift, source/UberRides/RidesClient.swift
Fixes #187 
PR will be changed to be based against `develop` once we merge #206 / #210 
* Adds two new initializers for AccessToken: `init(tokenString:refreshToken:expirationDate:grantedScopes:)` and `init?(oauthDictionary:)`
* Makes `AccessTokenFactory` public
* Adds additional test coverage to assert more parameters from JSON deserialization, and test new getters.
* Adds comments to document `AccessToken`'s `NSCoding` behavior
* Removes the `Codable` protocol from `AccessToken` since it won't be used for JSON serialization / deserialization
=> Fix manual access token creation bug

source/UberCore/Authentication/LoginButton.swift
By default, adding a LoginButton without sizing constraints to your view would make a 0x0 login button. 
I noticed this while testing the README last week, but also publicly reported [here](https://stackoverflow.com/questions/47502509/uber-login-not-working-correctly#comment81960895_47502509).
This is because we were missing a `sizeToFit()` call. See the `RideRequestButton`, for instance.
https://github.com/uber/rides-ios-sdk/blob/master/source/UberRides/RideRequestButton.swift#L168
This will also be rebased against `develop`
=> Fixed zero size login button

CHANGELOG.md, examples/Swift SDK/Swift SDK/AuthorizationCodeGrantExampleViewController.swift, examples/Swift SDK/Swift SDK/ImplicitGrantExampleViewController.swift, source/UberCore/UBSDKConstants.h, source/UberCore/UBSDKConstants.m, source/UberRides/Model/DistanceEstimate.swift, source/UberRides/Model/Driver.swift, source/UberRides/Model/PaymentMethod.swift, source/UberRides/Model/Place.swift, source/UberRides/Model/PriceEstimate.swift, source/UberRides/Model/Product.swift, source/UberRides/Model/Ride.swift, source/UberRides/Model/RideCharge.swift, source/UberRides/Model/RideEstimate.swift, source/UberRides/Model/RideMap.swift, source/UberRides/Model/RideParameters.swift, source/UberRides/Model/RideReceipt.swift, source/UberRides/Model/RideRequestLocation.swift, source/UberRides/Model/TimeEstimate.swift, source/UberRides/Model/UpfrontFare.swift, source/UberRides/Model/UserActivity.swift, source/UberRides/Model/UserProfile.swift, source/UberRides/Model/Vehicle.swift, source/UberRides/RideRequestButton.swift, source/UberRidesTests/ObjectMappingTests.swift
* Make Models Optional
* Update samples & CHANGELOG
=> Make models optional

examples/Swift SDK/Swift SDK/AuthorizationCodeGrantExampleViewController.swift, source/UberCore/Authentication/LoginManager.swift, source/UberCore/Authentication/LoginManagingProtocol.swift, source/UberCore/Authentication/UberAppDelegate.swift, source/UberCoreTests/LoginManagerTests.swift, source/UberCoreTests/UberAppDelegateTests.swift, source/UberCoreTests/UberMocks.swift
Fixed a bug where the system dialog box:
"<App Name>" wants to open "Uber"
Cancel / Open
would cause SSO to fail because the system dialog triggers the UIApplicationDidBecomeActive notification.
The fix is to make sure that the notification is preceded by a UIApplicationWillEnterForeground notification,
which happens only when the there's been a context switch to the Uber app.
Fixed a related bug where, if the user were to select Cancel in the system dialog box (above), the library
would attempt to use fallback to a web view, when the correct handling would be to stop attempting to log
in and return an error to the caller.
=> Fixed a bug where the system dialog box:

source/UberCore/Authentication/OAuthEndpoint.swift, source/UberCore/Networking/APIEndpoint.swift, source/UberCore/Networking/Request.swift, source/UberRides/EndpointsManager.swift, source/UberRidesTests/APIManagerTests.swift
This adds a `X-Uber-User-Agent` header to HTTP requests made by the SDK, just like the Android SDK.
In addition, I clean up the `HTTPHeader` and `HTTPMethod` enums. The Header enum seemed fairly useless, so I deleted it. `HTTPMethod` was conflicting with `Alamofire`, a popular Swift library, and is meant mostly for internal (Uber modules) use. Thus I renamed it to `UberHTTPMethod` to make developers lives easier. See #216.
=> Update HTTP Requests with Uber SDK Version Info

source/UberCore/Deeplinks/BaseDeeplink.swift, source/UberCore/Deeplinks/DeeplinkErrorType.swift, source/UberCore/Deeplinks/DeeplinkManager.swift, source/UberCore/Deeplinks/DeeplinkingProtocol.swift, source/UberCoreTests/BaseDeeplinkTests.swift, source/UberCoreTests/DeeplinkManagerTests.swift, source/UberRides.xcodeproj/project.pbxproj, source/UberRides/DeeplinkRequestingBehavior.swift, source/UberRides/RequestDeeplink.swift, source/UberRidesTests/DeeplinkRequestingBehaviorTests.swift, source/UberRidesTests/RequestDeeplinkTests.swift, source/UberRidesTests/RidesMocks.swift
This change allows deeplinks to specify a fallback if the original deeplink doesn't open properly.
We add a `fallbackURLs: [URL]` property to the `Deeplinking` protocol. The `BaseDeeplink` implements it and automatically adds the `Uber-enterprise` and `Uber-nightly` schemes if the original scheme is `uber`, to make beta testing easier. 
The `DeeplinkManager` is modified so that it uses the fallbacks if opening a deeplink is not successful. 
The `RequestDeeplink` and `DeeplinkRequestingBehavior` take an additional `DeeplinkFallbackType` enum in the initializer which defaults to `.mobileWeb`. Otherwise, it can fall back to `.appStore` or `.none`.
=> Add fallback to m.uber for Ride Request Deeplinks

README.md
If the Info.plist keys duplicated, Xcode will randomly choose one of them and ignores the other. This PR suggests users check if one of the keys already exists in their `Info.plist` file.
=> Updated readme file with note

source/UberCore/Authentication/LoginButton.swift
Currently, the text of the UILabel  `uberTitleLabel` is not being updated on the main thread, resulting in the text displayed not properly on screen in some cases.
I switched the operation to the main thread. `Self` is captured `weak` for better memory management.
Xcode warning:
=> Making UI update of LoginButton happening on the Main Thread

source/UberCore/Authentication/LoginManager.swift, source/UberCore/Configuration.swift, source/UberCoreTests/LoginManagerTests.swift
Adds a configuration option to use authorization code fallback rather than implicit, without requiring privileged scope.
This is the iOS implementation of this merged Android pull request: https://github.com/uber/rides-android-sdk/pull/128
=> Allows for using auth code fallback without priviledged scope

source/UberCore/Authentication/Tokens/AccessToken.swift, source/UberCoreTests/AccessTokenFactoryTests.swift, source/UberCoreTests/OAuthTests.swift, source/UberRidesTests/RidesClientTests.swift
`AccessToken` on the iOS version of the SDK doesn't include the `token_type` property, while this is available in the Android version of the SDK, and provided by the backend. 
To ensure consistency between versions of the SDK, the `token_type` property has been added to the `AccessToken` model. This has been verified as available and functioning correctly via unit tests, and a live integration of the SDK in a test application.
Screenshots are attached below of this change in action:
=> Added token_type property support to AccessToken model

source/UberCore/Authentication/LoginManager.swift
Source application will always be nil in iOS 13 when the Uber SDK is embedded in a 3rd party app.
=> iOS 13: Don't check for source application

.gitignore, Sources/UberAuth/AuthProviding.swift, Sources/UberAuth/Authorize/AuthenticationSession.swift, Sources/UberAuth/Authorize/AuthorizationCodeAuthProvider.swift, Sources/UberAuth/Authorize/AuthorizeRequest.swift, Sources/UberAuth/Authorize/PKCE.swift, Sources/UberAuth/Client.swift, Sources/UberAuth/Errors/UberAuthError.swift, Sources/UberAuth/Networking/Request.swift, Sources/UberAuth/Utilities/PlistParser.swift, examples/UberSDK/UberSDK.xcodeproj/project.pbxproj, examples/UberSDK/UberSDK/ContentView.swift, examples/UberSDK/UberSDK/Info.plist, examples/UberSDK/UberSDK/SelectionOptions.swift, examples/UberSDK/UberSDK/SelectionView.swift, examples/UberSDK/UberSDKTests/Mocks/UberAuthMocks.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizationCodeAuthProviderTests.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizeRequestTests.swift, examples/UberSDK/UberSDKTests/UberAuth/RequestTests.swift
This PR adds support for the auth code grant flow via In App login.
This will allow integrators to request an authorization code via Uber through ASWebAuthenticationSession only (native coming in the next PR).
Added a request class that is specific to auth related requests. This will also be used for PAR and any other auth types in the future.
There is an existing Request class in UberCore, however it is primarily used for Rides requests which may be stripped in the future.
A wrapper around ASWebAuthenticationSession to make launching and handling the result easier.
The main logic for the auth code grant flow. This class will be responsible for fetching request dependencies and making the network request to Uber auth.
Eventually it will also manage initiating native login and exchanging …
=> Adds support for Auth Code Grant Flow

Sources/UberAuth/Errors/README.md
Adding more documentation for the error types we can return from UberAuth
=> Adds README for Errors

Sources/UberAuth/Authorize/AuthorizationCodeAuthProvider.swift, Sources/UberAuth/Authorize/AuthorizeRequest.swift, Sources/UberAuth/Token/TokenRequest.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizationCodeAuthProviderTests.swift
Combining a few minor fixes for bugs found in UberAuth. Details below.
Scopes were not being sent in the Authorize request, only the default scope was being used in all cases. This PR adds logic to inject the scopes passed in the AuthContext into the authorize request and on to the backend.
There were certain scenarios where the ApplicationLauncher, a protocol representing UIApplication's openURL, could be called from a background thread. This wraps the only openURL call to ensure it is made from the main thread.
To support this change in testing, a closure can now be passed in to AuthorizationCodeAuthProvider allowing us to specify the AuthorizationSession to be used when launching in app auth.
We were incorrectly setting the form url encoded body for the TokenRequest as the url …
=> Add scope support, Fix TokenRequest

Sources/UberAuth/Button/LoginButton.swift, Sources/UberAuth/Utilities/Bundle.swift, Sources/UberCore/Colors.swift, Sources/UberCore/Utilities/Bundle.swift, Sources/UberRides/RideRequestButton.swift, Sources/UberRides/RidesCore/Utilities/Bundle.swift
With the introduction of Swift PM support, we started referencing bundles using Bundle.main. This breaks integration for anyone building manually or wrapping in a Cocoapods Podspec.
This change adds Bundle utilities to each framework that will select the correct bundle to load resources from. It will check the runtime argument SWIFT_PACKAGE to determine if we are in a Swift Package and use Bundle.module if so. Otherwise, it will target the bundle by class.
=> Adds Bundle utility

Sources/UberAuth/Authorize/AuthorizationCodeAuthProvider.swift, Sources/UberAuth/Authorize/AuthorizeRequest.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizationCodeAuthProviderTests.swift
This PR fixes a bug where we send code_challenge in the authorize request when we shouldn't be. We should only be sending a codeChallenge to the authorize endpoint in cases where we want to exchange auth code for auth token on device.
* Made AuthorizeRequest's `codeChallenge` property optional
* Changed AuthorizeRequest's payload to only set `code_challenge_method` if `codeChallenge` is non-nil
* From AuthorizationCodeAuthProvider, only send pace.codeChallenge if `shouldExchangeAuthCode` is true
* Added unit tests to verify `code_challenge` and `code_challenge_method` are not being sent for both inApp and native login destinations
=> Limit code_challenge to shouldExchangeAuthCode only

Sources/UberAuth/AuthProviding.swift, Sources/UberAuth/Authorize/AuthorizationCodeAuthProvider.swift, Sources/UberAuth/Authorize/AuthorizeRequest.swift, Sources/UberAuth/Authorize/Prompt.swift, examples/UberSDK/UberSDK/ContentView.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizationCodeAuthProviderTests.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizeRequestTests.swift
Implements the OpenID prompt query parameter to allow the integrating client to force either re-login or re-consent when issuing the authorize request. Details on the API [here](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
**Note:** Backend currently only supports `login` and `consent` parameters for inApp auth only. In the future we may add support for other parameters.
A new OptionSet that defines which prompt parameters to send to the authorize request. Multiple values are supported, they will be sent space delimited and will be url encoded in the requests query parameters.
Updated the AuthorizeRequest to accept prompt as a parameter. If supplied it will send it as an additional query parameter.
Also added prompt as a parameter here, which will get injected into …
=> Implement prompt for re-login/consent

Package.swift, Sources/UberCore/UberButton.swift
The current min iOS version defined in the Package file is v15. The only API restricting this is UIButton.Configuration. This PR provides a fallback for the UIButton configuration and drops the iOS version to v14.
* Min OS version v15 -> v14
* Marked `extension UIButton.Configuration` as `@available(iOS 15...)`
* Added code to configure UIButton using old APIs compatible with iOS 14-
=> Drop min OS version to iOS 14

Sources/UberAuth/Authorize/AuthorizationCodeAuthProvider.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizationCodeAuthProviderTests.swift
Adding support for the prompt OAuth parameter when executing native auth. We do not want to support the login option when launching the native 1P app, so this is removed before launching. Only the consent option should work for native auth.
Added unit tests to ensure the login prompt value is not sent for native requests
1. Run the sample app
2. Set `Destination` to Native
3. Toggle `Always ask for Login` and `Always ask for Consent` to on
4.  Verify the native app was launched and only consent was required, not login
=> Prompt parameter for native auth

Sources/UberAuth/AuthProviding.swift, Sources/UberAuth/Authorize/AuthorizationCodeAuthProvider.swift, Sources/UberAuth/UberAuth.swift, examples/UberSDK/UberSDK/ContentView.swift, examples/UberSDK/UberSDKTests/Mocks/Mocks.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthManagerTests.swift
Adding a new top-level API to UberAuth to "logout" the current user. This function deletes the stored auth token by:
1. If UberAuth has a stored currentContext, calls the logout API on the currentContext
2. If UberAuth does not have a stored currentContext, uses an internal TokenManager instance and deletes the token saved under the default identifier.
The equivalent API has been added to AuthorizationCodeAuthProvider to delete the token as described in (2).
After token deletion, UberAuth will release the stored currentContext.
Another computed property `isLoggedIn` was added for convenience to determine if a token exists in the keychain.
Added new static and instance methods to UberAuth for logout as described above. Added computed isLoggedIn property to determine auth state.
Added …
=> Logout API

Sources/UberAuth/Authorize/AuthorizationCodeAuthProvider.swift, Sources/UberCore/ApplicationLauncher.swift, examples/UberSDK/UberSDKTests/Mocks/Mocks.swift, examples/UberSDK/UberSDKTests/UberAuth/AuthorizationCodeAuthProviderTests.swift
Made minor updates required to build/run on Xcode 16. Only one change was required to handle UIApplication.openUrl
UIApplication's open(url...) method signature changed. Since the ApplicationLaunching protocol redefined this method and we had a UIApplication extension conforming to ApplicationLaunching, this broke.
To fix this, open(url) was changed to launch(url) and the method is not called internally in the extension.
Manually tested both inApp and native auth on simulator and physical devices
Mocks + unit tests were updated
=> Xcode 16 Support

README.md, documentation/migration-guide-2.0.0.md
Adding a migration guide to assist with updating from `0.1x.0` to 2.0.0-beta` (once released)
=> Add migration guide for 2.0.0

Sources/UberCore/Colors.swift, Sources/UberRides/RideRequestButton.swift
Swift PM supports referencing bundles using Bundle.main. This breaks integration for anyone building manually or wrapping in a Cocoapods Podspec.
This change uses bundle utilities in each framework to select the correct bundle to load resources from.
=> Uses Bundle utility
